apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aktivitetskrav-backend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{image}}
  replicas:
    min: {{replicas_min}}
    max: {{replicas_max}}
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health
  readiness:
    path: /internal/health
  startup:
    path: /internal/health
    initialDelay: 40
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      memory: {{memory}}
    requests:
      cpu: {{cpu}}
      memory: {{memory}}
  kafka:
    pool: {{kafkaPool}}
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: ditt-sykefravaer
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: {{db_tier}}
        diskType: SSD
        highAvailability: true
        diskSize: 10
        pointInTimeRecovery: false
        diskAutoresize: true
        databases:
          - name: aktivitetskrav-backend-db
            users:
              - name: bigquery-datastream
            envVarPrefix: DATABASE
        maintenance:
          day: 2
          hour: 2
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  env:
  {{#each env}}
     - name: {{@key}}
       value: "{{this}}"
  {{/each}}
