apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aktivitetskrav-backend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/health/livenessState
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/health/readinessState
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
    autoInstrumentation:
      enabled: true
      runtime: java
  ingresses:
    - "https://aktivitetskrav-backend.intern.dev.nav.no"
  resources:
    limits:
      memory: 800Mi
    requests:
      memory: 800Mi
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: esyfo-proxy
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        diskType: SSD
        highAvailability: true
        diskSize: 10
        pointInTimeRecovery: false
        diskAutoresize: true
        name: aktivitetskrav-backend-db-instance
        databases:
          - name: aktivitetskrav-backend-db
            envVarPrefix: DB
            users:
              - name: bigquery-datastream
        maintenance:
          day: 2
          hour: 2
        flags:
          - name: cloudsql.logical_decoding
            value: "on"
  env:
    - name: ESYFO_PROXY_CLIENT_ID
      value: dev-gcp:team-esyfo:esyfo-proxy
