name: Build & Deploy
on: push

jobs:
  jar-app:
    uses: navikt/teamesyfo-github-actions-workflows/.github/workflows/spring-boot.yaml@add-spring-boot-workflow
    permissions:
      actions: read
      contents: read
      security-events: write
      packages: write
      id-token: write
    secrets: inherit
    with:
      app: aktivitetskrav-backend
